repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.7.2
    hooks:
      - id: shellcheck
      # args: ["--severity=warning"]  # Optionally only show errors and warnings
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-1
    hooks:
      - id: shfmt
        args:
          - -d
          - -i
          - "2"
